
plugins:
  - jekyll-remote-theme # Ensure the remote theme plugin is enabled
  - jekyll-seo-tag      # Add SEO optimization
  - jekyll-sitemap      # Generate a sitemap for better indexing
  - jekyll-feed         # Add RSS feed support

gem "github-pages", group: :jekyll_plugins

title: "Gaku Amano"
description: "Software Engineer | Crafting elegant solutions for complex problems"
author: "Gaku Amano"
email: "no13masterpiece@gmail.com"
social_links:
  github: "https://github.com/gakuaman13"
  linkedin: "https://linkedin.com/in/gakuamano13"